/*
MYSQL DATA TRANSFER
SOURCE HOST: localhost
SOURCE DATABASE: DragonDiamante
DATE: 09/02/2018  11:10 am
*/
DROP DATABASE IF EXISTS 'DragonDiamante';
CREATE DATABASE DragonDiamante;
use DragonDiamante

CREATE 